default_platform(:ios)

platform :ios do
  desc "Build the iOS app for simulator"
  lane :build do
    xcodebuild(
      project: "CICDLabApp/CICDLabApp.xcodeproj",
      scheme: "CICDLabApp",
      destination: "generic/platform=iOS Simulator"
    )
  end

  desc "Increment the iOS build number"
  lane :increment_build do
    increment_build_number(
      xcodeproj: "CICDLabApp/CICDLabApp.xcodeproj"
    )
  end

  desc "Run iOS tests"
  lane :test do
    scan(
      project: "CICDLabApp/CICDLabApp.xcodeproj",
      scheme: "CICDLabApp",
      device: "iPhone 16"
    )
  end

  desc "Archive the iOS app"
  lane :archive do
    gym(
      project: "CICDLabApp/CICDLabApp.xcodeproj",
      scheme: "CICDLabApp",
      configuration: "Release",
      skip_package_ipa: true,
      destination: "generic/platform=iOS"
    )
  end  
end